# SPDX-License-Identifier: GPL-3.0-or-later

# system-banner.nix
{
  config,
  lib,
  pkgs,
  ...
}:

with lib;

let
  cfg = config.programs.system-banner;
in
{
  options.programs.system-banner = {
    enable = mkEnableOption "system banner on shell login";

    shellHook = mkOption {
      type = types.str;
      default = "";
      description = "Additional shell commands to run after displaying the system banner";
    };

    showOnLogin = mkOption {
      type = types.bool;
      default = true;
      description = "Whether to show the banner on interactive shell login";
    };
  };

  config = mkIf cfg.enable {
    environment.systemPackages = with pkgs; [
      bc # Required for some calculations in the script
    ];

    # Create the script at /etc/system-banner.sh
    environment.etc."system-banner.sh" = {
      mode = "0755";
      text = ''
        #!/bin/sh

        # System Status Banner Script
        # Generated by NixOS configuration

        # ANSI color codes
        RED='\033[0;31m'
        GREEN='\033[0;32m'
        YELLOW='\033[0;33m'
        BLUE='\033[0;34m'
        MAGENTA='\033[0;35m'
        CYAN='\033[0;36m'
        WHITE='\033[1;37m'
        BOLD='\033[1m'
        RESET='\033[0m'

        # Clear screen and move to top
        clear

        # System hostname
        echo -e "''${BOLD}''${BLUE}╔════════════════════════════════════════════════════════════╗''${RESET}"
        echo -e "''${BOLD}''${BLUE}║                     ''${WHITE}SYSTEM INFORMATION''${BLUE}                     ║''${RESET}"
        echo -e "''${BOLD}''${BLUE}╚════════════════════════════════════════════════════════════╝''${RESET}"

        # Hostname and date
        echo -e "''${CYAN}Hostname:    ''${GREEN}$(hostname)''${RESET}"
        echo -e "''${CYAN}Date & Time: ''${GREEN}$(date)''${RESET}"
        echo

        # OS Information
        echo -e "''${BOLD}''${MAGENTA} == OS INFO ''${RESET}"
        echo -e "''${CYAN}OS:         ''${GREEN}$(uname -o 2>/dev/null || echo "$(uname -s)")''${RESET}"
        echo -e "''${CYAN}Kernel:     ''${GREEN}$(uname -r)''${RESET}"
        echo -e "''${CYAN}Arch:       ''${GREEN}$(uname -m)''${RESET}"
        echo -e "''${CYAN}Shell:      ''${GREEN}$SHELL''${RESET}"
        echo -e "''${CYAN}Distro:     ''${GREEN}NixOS''${RESET}"

        # Get NixOS version if available
        if [ -f /etc/os-release ]; then
            . /etc/os-release
            echo -e "''${CYAN}Release:    ''${GREEN}$VERSION_ID''${RESET}"
        fi
        echo

        # Uptime & Load Average
        echo -e "''${BOLD}''${MAGENTA} == UPTIME & LOAD''${RESET}"
        echo -e "''${CYAN}Uptime:     ''${GREEN}$(uptime | cut -f2 -d'p' | cut -f1 -d',' | tr -d ' ')''${RESET}"
        echo -e "''${CYAN}Users:      ''${GREEN}$(uptime | cut -f2 -d',' | cut -f3- -d' ')''${RESET}"
        echo -e "''${CYAN}Load Avg:   ''${GREEN}$(uptime | cut -f5 -d':' | cut -f2- -d' ')''${RESET}"
        echo

        # CPU Information
        echo -e "''${BOLD}''${MAGENTA} == CPU INFO''${RESET}"
        if [ -f /proc/cpuinfo ]; then
            CPU_MODEL=$(grep "model name" /proc/cpuinfo | head -1 | cut -d ":" -f2 | sed 's/^[ \t]*//')
            CPU_CORES=$(grep -c "processor" /proc/cpuinfo)
            echo -e "''${CYAN}CPU Model:  ''${GREEN}$CPU_MODEL''${RESET}"
            echo -e "''${CYAN}CPU Cores:  ''${GREEN}$CPU_CORES''${RESET}"
        else
            echo -e "''${CYAN}CPU Info:   ''${YELLOW}Could not determine''${RESET}"
        fi
        echo

        # Memory Information
        echo -e "''${BOLD}''${MAGENTA} == MEMORY INFO''${RESET}"
        if [ -f /proc/meminfo ]; then
            # Linux
            MEM_TOTAL=$(grep "MemTotal" /proc/meminfo | awk '{print $2/1024/1024 " GB"}')
            MEM_FREE=$(grep "MemAvailable" /proc/meminfo | awk '{print $2/1024/1024 " GB"}' 2>/dev/null ||
                      grep "MemFree" /proc/meminfo | awk '{print $2/1024/1024 " GB"}')

            echo -e "''${CYAN}Total RAM:  ''${GREEN}$MEM_TOTAL''${RESET}"
            echo -e "''${CYAN}Free RAM:   ''${GREEN}$MEM_FREE''${RESET}"
        else
            echo -e "''${CYAN}Memory:     ''${YELLOW}Could not determine''${RESET}"
        fi
        echo

        # Disk Usage
        echo -e "''${BOLD}''${MAGENTA} == DISK USAGE''${RESET}"
        if command -v df >/dev/null 2>&1; then
            # Get disk usage for main partitions, skip temporary and special filesystems
            printf "''${CYAN}%-25s %-8s %-8s %-8s %-5s''${RESET}\n" "Filesystem" "Size" "Used" "Avail" "Use%"
            printf "''${CYAN}%-25s %-8s %-8s %-8s %-5s''${RESET}\n" "-------------------------" "--------" "--------" "--------" "-----"

            df -h 2>/dev/null | grep -v "tmp\|none\|udev\|shm\|Filesystem" | grep -v '^Filesystem' |
            while read line; do
                # Parse each line of df output
                MOUNT=$(echo "$line" | awk '{print $NF}')
                SIZE=$(echo "$line" | awk '{print $2}')
                USED=$(echo "$line" | awk '{print $3}')
                AVAIL=$(echo "$line" | awk '{print $4}')
                PERCENT=$(echo "$line" | awk '{print $5}')

                # Color the percentage based on severity
                if [[ "$PERCENT" == *"100%"* ]]; then
                    PCT_COLOR=$RED
                elif [[ $(echo "$PERCENT" | tr -d '%') -gt 90 ]]; then
                    PCT_COLOR=$RED
                elif [[ $(echo "$PERCENT" | tr -d '%') -gt 75 ]]; then
                    PCT_COLOR=$YELLOW
                else
                    PCT_COLOR=$GREEN
                fi

                # Format and print the line with truncation for long filesystem names
                MOUNT_SHORT="$MOUNT"
                # Add truncation logic
                if [ $(echo "$MOUNT" | wc -c) -gt 24 ]; then
                    MOUNT_SHORT=$(echo "$MOUNT" | cut -c 1-23)"+"
                fi

                printf "''${CYAN}%-25s ''${GREEN}%-8s ''${YELLOW}%-8s ''${GREEN}%-8s ''${PCT_COLOR}%-5s''${RESET}\n" \
                       "$MOUNT_SHORT" "$SIZE" "$USED" "$AVAIL" "$PERCENT"
            done
        else
            echo -e "''${YELLOW}Disk usage information not available''${RESET}"
        fi
        echo

        # Network Information
        echo -e "''${BOLD}''${MAGENTA} == NETWORK INFO''${RESET}"

        # Display IP addresses
        if command -v ip >/dev/null 2>&1; then
            # Modern Linux systems with 'ip' command
            ip -4 addr show | grep -v 127.0.0.1 | grep "inet " | while read line; do
                IFACE=$(echo "$line" | awk '{print $NF}')
                IP=$(echo "$line" | awk '{print $2}' | cut -d/ -f1)
                echo -e "''${CYAN}$IFACE: ''${GREEN}$IP''${RESET}"
            done
        elif command -v ifconfig >/dev/null 2>&1; then
            # For macOS and older Linux systems
            ifconfig | grep -E "inet " | grep -v 127.0.0.1 | while read line; do
                IFACE=$(echo "$line" | awk -F: '{print $1}')
                IP=$(echo "$line" | awk '{print $2}')
                echo -e "''${CYAN}$IFACE: ''${GREEN}$IP''${RESET}"
            done
        else
            echo -e "''${YELLOW}IP information not available''${RESET}"
        fi

        # Run any additional scriptlets specified in the shellHook option
        ${cfg.shellHook}
      '';
    };

    # Add to all user shells if showOnLogin is enabled
    programs.bash.interactiveShellInit = mkIf cfg.showOnLogin ''
      # Display system banner on login for interactive shells
      if [[ $- == *i* ]]; then
        /etc/system-banner.sh
      fi
    '';

    programs.zsh.interactiveShellInit = mkIf cfg.showOnLogin ''
      # Display system banner on login for interactive shells
      if [[ $- == *i* ]]; then
        /etc/system-banner.sh
      fi
    '';
  };
}
