# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.24)
{
  # A helpful description of your flake
  description = "System configurations";

  # Flake inputs
  inputs = {
    flake-schemas.url =
      "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
    home-manager = {
      url = "path:./home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # Flake outputs that other flakes can use
  outputs = { self, flake-schemas, home-manager, nixpkgs }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" "aarch64-darwin" ];
      forEachSupportedSystem = f:
        nixpkgs.lib.genAttrs supportedSystems
        (system: f { pkgs = import nixpkgs { inherit system; }; });
    in {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [ curl git jq wget nixpkgs-fmt ];

          # A hook run every time you enter the environment
          shellHook = ''
            echo "Entering nix shell!"
          '';
        };
      });
      homeConfigurations."bobby" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.aarch64-darwin;
        modules = [ ./home-manager/default.nix ];
      };
    };
}
