# SPDX-License-Identifier: GPL-3.0-or-later

.ONESHELL:
SHELL := /bin/zsh
.SHELLFLAGS := -e -c
MAKEFLAGS += --no-print-directory
.PHONY: help build clean switch deploy-% update check format clean test-build-% provision

BOLD  = \033[1m
RED = \033[0;31m
GREEN = \033[0;32m
YELLOW = \033[0;33m
BLUE = \033[0;34m
PINK= \033[35m
BOLD = \033[1m
RESET = \033[0m
success_msg = echo -e "$(BOLD)$(GREEN)$(1)$(RESET)"
error_msg = echo -e "$(BOLD)$(RED)$(1)$(RESET)"
info_msg = echo -e "$(BOLD)$(YELLOW)$(1)$(RESET)"
title_msg = echo -e "$(BOLD)$(BLUE)$(1)$(RESET)"

help_width = 30
help_option = @printf "$(BOLD)%-$(help_width)s$(RESET)%s\n" $(1) $(2)
help_option_highlight = @printf "$(BOLD)$(PINK)%-$(help_width)s$(RESET)%s\n" $(1) $(2)

# Get list of hosts from $(DEPLOY_YAML)
DEPLOY_YAML := deploy.yaml
HOSTS := $(shell yq eval '.hosts | keys | .[]' $(DEPLOY_YAML))

# Helper functions to get host metadata
get-host-user = $(shell yq eval '.hosts."$(1)".targetUser' $(DEPLOY_YAML))
get-host-ip = $(shell yq eval '.hosts."$(1)".targetHost' $(DEPLOY_YAML))
get-build-on-target = $(shell yq eval '.hosts."$(1)".buildOnTarget' $(DEPLOY_YAML))
get-host-tags = $(shell yq eval '.hosts."$(1)".tags[]' $(DEPLOY_YAML))
get-host-smoketests = $(shell yq eval '.hosts."$(1)".smoketests' $(DEPLOY_YAML))

# Overrides
export NIXBUILD_USER ?=
ifdef NIXBUILD_USER
get-host-user = $(NIXBUILD_USER)
endif

# Default target
help:
	@$(call title_msg,"Nix Development 🧪")
	$(call help_option_highlight,"devshell","Enter devshell")
	$(call help_option_highlight,"update","Update flake inputs")
	$(call help_option_highlight,"check","Check flake and run basic tests")
	$(call help_option_highlight,"home-switch","Switch to the new home-manager config locally")
	$(call help_option,"update-nix-conf","Update '/etc/nix' with './etc/nix'")
	$(call help_option,"format","Format Nix files")
	$(call help_option,"flake-info","Show flake info")
	$(call help_option,"dry-store-gc","Nix store garbage collection (dry run)")
	$(call help_option,"store-gc","Nix store garbage collection")
	@echo
	@$(call title_msg,"Host Access 🏘️")
	$(call help_option_highlight,"list-hosts","List all hosts with their metadata")
	$(call help_option_highlight,"status","Ping hosts to check if they are up")
	$(call help_option,"info-HOST","Show info for specific host")
	$(call help_option,"ssh-HOST","SSH into host")
	@echo
	@$(call title_msg,"Deployment \(use \"all\" for all hosts\) 🔄")
	$(call help_option_highlight,"update-hardware-HOST","Replace hardware-configuration with one generated by nixos-generate-config")
	$(call help_option_highlight,"build-HOST","Build HOST configuration using nixos-rebuild on HOST")
	$(call help_option_highlight,"test-HOST","Build HOST and activate the new configuration")
	$(call help_option_highlight,"switch-HOST","Build HOST and activate the new configuration and make it the boot default")
	$(call help_option_highlight,"rollback-HOST","Roll back HOST to the previous configuration")
	$(call help_option_highlight,"apply-HOST","Run the 'test' 'switch' 'reboot' and 'smoketests' for the HOST")
	$(call help_option,"diff-HOST","Show configuration diff for host")
	$(call help_option,"dry-activate-HOST","Build HOST configuration and show what changes would be performed by the activation")
	$(call help_option,"reboot-HOST","Reboot HOST")
	$(call help_option,"reboot-test-HOST","Reboot HOST and run smoketests")
	$(call help_option,"switch-test-HOST","Switch HOST and run smoketests after")
	$(call help_option,"smoketests-HOST","Run HOST smoketests")
	@echo
	@$(call title_msg,"Raspberry Pi Builds 🍓")
	$(call help_option,"HOST-installer","Build Arm64 image for Raspberry Pi using Docker")
	$(call help_option,"write-sd-HOST DEVICE","Write Arm64 image for Raspberry Pi to '/dev/rdiskX'")
	@echo
	@$(call title_msg,"SOPS Secrets Management 🤫")
	$(call help_option,"sops-init","Generate barebones '.sops.yaml'")
	$(call help_option,"sops-add-user","Add user to '.sops.yaml'")
	$(call help_option,"sops-add-host-keys","Add host keys to '.sops.yaml'")
	$(call help_option,"sops-update-keys","Update '.sops.yaml' keys if new hosts were added")
	$(call help_option,"sops-add-host-secrets-HOST","Create new secrets file './secrets/HOST.yaml'")
	$(call help_option,"sops-edit-HOST","Edit secrets for './secrets/HOST.yaml'")
	$(call help_option,"sops-status","Check host age keys and whether './secrets/secrets.yaml' can be decrypted")

# Home-manager dev shell
devshell:
	nix develop

# Update flake inputs
update:
	nix flake update
	nix flake update --flake ./home-manager
	$(call success_msg,"Flake inputs updated. Consider running 'make deploy-all' to apply updates.")

update-nix-conf:
	@$(call info_msg,"Backing up files...")
	@cp -v /etc/nix/machines /etc/nix/machines.old
	@cp -v ./etc/nix/machines /etc/nix/machines
	@cp -v /etc/nix/nix.custom.conf /etc/nix/nix.custom.conf.old
	@cp -v ./etc/nix/nix.custom.conf /etc/nix/nix.custom.conf
	@$(call info_msg,"Restarting nix-daemon...")
	@launchctl kickstart -k system/systems.determinate.nix-daemon
	@$(call success_msg,"Done")

# Check flake and run basic tests
check:
	@nix flake check
	@$(call success_msg,"✓ Flake check passed")
	@$(call info_msg,"Testing host configurations..."); \
	for host in $(HOSTS); do \
		nix build .#nixosConfigurations."$$host".config.system.build.toplevel --dry-run; \
	done; \
	$(call success_msg,"✓ All host configurations are valid")

# Format Nix files
format:
	find . -name "*.nix" -exec nixfmt {} \;
	@$(call success_msg,"✓ All Nix files formatted")

# Home manager switch
home-switch:
	nix run home-manager -- switch --flake ./home-manager

# Show flake info
flake-info:
	nix flake show

dry-store-gc:
	nix store gc -v --dry-run
	@$(call success_msg,"✓ Garbage collection completed (dry run)")

store-gc:
	nix store gc --debug
	@$(call success_msg,"✓ Garbage collection completed")

# Quick status check
status:
	@$(call info_msg,"Checking host connectivity..."); \
	for host in $(HOSTS); do \
		if ping -c 1 -W 2 "$$host.local" >/dev/null 2>&1; then \
			$(call success_msg,"✓ $$host: Online"); \
			continue; \
		fi; \
		$(call error_msg,"✗ $$host: Offline"); \
	done

# SSH using metadata
ssh-%:
	@ip=$(call get-host-ip,$*)
	@user=$(call get-host-user,$*)
	@$(call info_msg,"Connecting to $* as $$user@$$ip...")
	@ssh $$user@$$ip

# List all hosts with their metadata
list-hosts:
	@$(foreach host,$(HOSTS), \
		$(call title_msg,"$(host):"); \
		echo "    IP: $(call get-host-ip,$(host))"; \
		echo "    User: $(call get-host-user,$(host))"; \
		echo "    Tags: $(shell yq eval '.hosts."$(host)".tags | join(", ")' $(DEPLOY_YAML))"; \
		echo ""; \
	)

# Show info for specific host
info-%:
	@$(call title_msg,"Host: $*")
	@echo "IP: $(call get-host-ip,$*)"
	@echo "BuildOnTarget: $(call get-build-on-target,$*)"
	@echo "User: $(call get-host-user,$*)"
	@echo "Tags: $(call get-host-tags,$*)"

# Update Hardware
#
# Updates the host 'hardware-configuration.nix' with one generated by
# 'nixos-generate-config'.
update-hardware-%:
	@./scripts/nixos-rebuild.sh update-hardware $*

# Build
#
# Build the new configuration, but neither activate it nor add it to the
# GRUB boot menu.
build-%:
	@./scripts/nixos-rebuild.sh build $*

# Dry Build
#
# Show what store paths would be built or downloaded by any of the operations
# above, but otherwise do nothing.
dry-build-%:
	@./scripts/nixos-rebuild.sh dry-build $*

# Dry Activate
#
# Build the new configuration, but instead of activating it, show what
# changes would be performed by the activation. The list of changes is not
# guaranteed to be complete.
dry-activate-%:
	@./scripts/nixos-rebuild.sh dry-activate $*

# Test
#
# Build and activate the new configuration, but do not add it to the GRUB
# boot menu. Thus, if you reboot the system (or if it crashes), you will
# automatically revert to the default configuration.
test-%:
	@./scripts/nixos-rebuild.sh test $*

# Switch
#
# Build and activate the new configuration, and make it the boot default.
# That is, the configuration is added to the GRUB boot menu as the default menu
# entry, so that subsequent reboots will boot the system into the new
# configuration.
#
# Previous configurations activated with nixos-rebuild switch or nixos-rebuild
# boot remain available in the GRUB menu.
switch-%:
	@./scripts/nixos-rebuild.sh switch $*
switch-test-%:
	$(MAKE) switch-$* smoketests-$*

# Rollback
#
# Instead of building a new configuration as specified by
# /etc/nixos/configuration.nix, roll back to the previous configuration.
# (The previous configuration is defined as the one before the “current”
# generation of the Nix profile /nix/var/nix/profiles/system.)
rollback-%:
	@echo "TODO"

reboot-%:
	@./scripts/nixos-rebuild.sh reboot $*
reboot-test-%:
	$(MAKE) reboot-$* smoketests-$*

smoketests-%:
	@$(call get-host-smoketests,$*) $*

apply-%:
	$(MAKE) test-$* switch-$* reboot-$* smoketests-$*

# Switch All
#
# Runs 'make switch-HOST' for each host.
switch-all:
	@$(call info_msg,"Deploying to all hosts...")
	@for host in $(HOSTS); do \
		$(MAKE) deploy-$$host; \
	done
	@$(call success_msg,"✓ All deployments complete")

# Show configuration diff for a host
diff-%:
	nixos-rebuild dry-run --flake .#$* --target-host $(HOST).local

# Build SD card image for Pi5
NIX_DOCKER_VOLUME ?= nix-store-cache
NIX_DOCKER_IMAGE ?= nixos/nix:2.30.1-arm64

# Build aarch64 artifacts using Docker
aarch64-sdimage-%:
	@./scripts/provision/linux-aarch64-docker-build.sh installerConfigurations.$* sd-image/nixos-sd-image-r$*-uboot.img.zst

aarch64-kexec:
	@./scripts/provision/linux-aarch64-docker-build.sh installerConfigurations.aarch64-kexec nixos-kexec-installer-aarch64-linux.tar.gz

%-installer: aarch64-sdimage-% aarch64-kexec
	@$(call success_msg,"✓ $* installers complete \(SD image + kexec\)")

# Write image to SD card
write-sd-%:
	@if [ -z "$(DEVICE)" ]; then \
		$(call error_msg,"Usage: make write-sd-$* DEVICE=/dev/rdiskX"); \
		exit 1; \
	fi
	@if [ ! -f "./result/nixos-sd-image-r$*-uboot.img.zst" ] || [ ! -f "./result/nixos-kexec-installer-aarch64-linux.tar.gz" ]; then \
		$(call error_msg,"No $* installer found. Run 'make $*-installer' first"); \
		exit 1; \
	fi
	@sudo fdisk $(DEVICE)
	@$(call info_msg,"WARNING: This will erase all data on $(DEVICE)!")
	@bash -c 'read -p "Continue? (y/N) " -n 1 -r; \
	echo; \
	if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
		pi_img="./result/nixos-sd-image-r$*-uboot.img"; \
		$(call info_msg,"Uncompressing $$pi_img.zst..."); \
		if [ ! -f "$${pi_img}" ]; then \
			zstd -d "$${pi_img}.zst" -o "$${pi_img}"; \
		fi; \
		$(call info_msg,"Begin writing $$pi_img to $(DEVICE)..."); \
		sudo dd if="$${pi_img}" of=$(DEVICE) bs=1M status=progress; \
		$(call success_msg,"Done! The Pi will boot with SSH enabled."); \
		$(call info_msg,"Default user: nixos"); \
		$(call info_msg,"Your SSH key is already installed"); \
		$(call success_msg,"Safely eject '$(DEVICE)' and boot the $*"); \
	fi'

provision:
	$(call title_msg,"HOSTS = $(HOSTS)")
	@$(call info_msg,"Run the './scripts/provision/linux-HOSTARCH.sh' script")

# clean-reboot
clean-reboot/%:
	@echo TODO

# SOPS targets
sops-init:
	@./scripts/sops/init.sh

sops-add-user:
	@./scripts/sops/add-user.sh

sops-add-host-keys:
	@./scripts/sops/add-host-keys.sh

sops-add-host-secrets-%:
	@./scripts/sops/add-host-secrets.sh $*

sops-update-keys:
	@sops updatekeys secrets/secrets.yaml

sops-edit-%:
	@sops edit secrets/$*.yaml

sops-status:
	@./scripts/sops/status.sh

clean:
	git clean -xfd
