# Written by https://github.com/DeterminateSystems/nix-installer.
# The contents below are based on options specified at installation time.

# The docs about trusted-users say that adding users there essentially
# give that user root rights. So let's not do that and instead configure
# the builder machine in /etc/nix/machines.
#
trusted-users = @admin
builders = @/etc/nix/machines

# Enable cross-compilation
extra-platforms = aarch64-linux x86_64-linux

# Add substituters
extra-substituters = https://cache.nixos.org https://nixos-raspberrypi.cachix.org
extra-trusted-substituters = https://cache.nixos.org https://nixos-raspberrypi.cachix.org
extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nixos-raspberrypi.cachix.org-1:4iMO9LXa8BqhU+Rpg6LQKiGa2lsNh/j2oiYLNOQ5sPI=
