#!/usr/bin/env bash

. ./scripts/sops/common.sh

set -euo pipefail

# Backup existing config if it exists
if [[ -f "$SOPS_CONFIG" ]]; then
	cp "$SOPS_CONFIG" "${SOPS_CONFIG}.backup-$(date +%Y%m%d-%H%M%S)"
	info "Backed up existing config"
fi

info "Creating SOPS configuration..."

# Create barebones .sops.yaml
cat >"$SOPS_CONFIG" <<EOF
# SOPS configuration for NixOS homelab
# WARNING: Do not edit directly
# Generated by ${0} on $(date)

keys:
creation_rules:
  - path_regex: ^${SECRETS_FILE}\$
    key_groups:
    - pgp:
      age:
EOF

success "Generated '$SOPS_CONFIG':"
yq eval -P "$SOPS_CONFIG"
