#!/usr/bin/env bash

. ./scripts/sops/common.sh

set -euo pipefail

# Backup existing config if it exists
if [[ -f "$SOPS_CONFIG" ]]; then
	cp "$SOPS_CONFIG" "${SOPS_CONFIG}.backup-$(date +%Y%m%d-%H%M%S)"
	info "Backed up existing config"
fi

# Get admin public key
ADMIN_AGE_KEY=$(ssh-to-age -i "$ED_PUBKEY_PATH")
ADMIN_NAME=$(whoami)

info "Creating SOPS configuration..."

# Create .sops.yaml
cat >"$SOPS_CONFIG" <<EOF
# SOPS configuration for NixOS homelab
# WARNING: Do not edit directly
# Generated by ${0} on $(date)

creation_rules:
  - path_regex: ^${SECRETS_FILE}\$
    key_groups:
      - age:
          - ${ADMIN_AGE_KEY} # $ED_PUBKEY_PATH
EOF

success "Generated '$SOPS_CONFIG'"
yq -s "." "$SOPS_CONFIG"
info "Admin user: ${ADMIN_NAME}"
info "Admin public key: ${ADMIN_AGE_KEY}"
