#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

. ./scripts/sops/__base__

set -euo pipefail

# Backup existing config if it exists
if [[ -f "$SOPS_CONFIG" ]]; then
    sops_backup="${SOPS_CONFIG}.backup-$(date +%Y%m%d-%H%M%S)"
    cp "$SOPS_CONFIG" "$sops_backup"
    info "backed up existing config to '$sops_backup'"
fi

# Create barebones .sops.yaml
info "creating SOPS configuration at '$SOPS_CONFIG'..."
cat >"$SOPS_CONFIG" <<EOF
# SOPS configuration for NixOS homelab
# WARNING: any modifications will be overwritten by '$(dirname "$0")' scripts
# Generated by '${0}' on $(date)

keys:
creation_rules:
  # The first rule is for the global secrets file shared by all hosts. All hosts
  # age keys are added here by default.
  - path_regex: ^${SECRETS_FILE}\$
    key_groups:
    - pgp:
      age:
EOF

pass "Generated '$SOPS_CONFIG':"
print_yaml "$SOPS_CONFIG"
